### 
POST http://localhost:5000/api/v1/ventas HTTP/1.1
Content-Type: application/json

{
   "store_name": "Stirpe",
   "client":{
        "id_client": 1192801018,
        "name": "Juan Esteban A",
        "addres": {
            "city":"Manizales",
            "birthday": "2000/12/28",
            "code_zip":"17001"
        }
   },

   "invoice":{
        "articles":{
            "product":["Jean","Glass","belt"],
            "amount":["1,1,1"],
            "price":["100,100,300"]
        },
        "pay":{"cash": true}
   }
}

###
GET http://localhost:5000/api/v1/ventas  HTTP/1.1

###
GET http://localhost:5000/api/v1/ventas/ HTTP/1.1

###
PUT http://localhost:5000/api/v1/ventas/640b674878bfafb03656c8f7 HTTP/1.1
Content-Type: application/json


{
   "store_name": "Falabella Colombia",
   "client":{
        "id_client": 75105790,
        "name": "Alejandro Londoño",
        "addres": {
            "city":"Manizales",
            "birthday": "2000/12/28",
            "code_zip":"17001"
        }
   },

   "invoice":{
        "articles":{
            "product":["T-Shirt","Shoes","Dress"],
            "amount":["1,2,1"],
            "price":["100,1000,300"]
        },
        "pay":{"cash": true}
   }
}

###
DELETE http://localhost:5000/api/v1/ventas/640b69d26a2e90bdd556b28d HTTP/1.1

###
DELETE http://localhost:5000/api/v1/ventas  HTTP/1.1